(* Machine-checked proof, against WasmCert-Coq's real formal semantics of
   WebAssembly, that the `add` function defined in add.wat computes 32-bit
   wrapping addition -- i.e. that invoking it on any two i32 arguments
   reduces, through the actual small-step operational semantics, to
   Wasm_int.Int32.iadd of those arguments. Consolidated from what was
   originally six files (AddBytes/AddAst/AddCorrespondence/AddInvoke/
   AddSteps/AddCorrect) into this one; the section comments below mark
   those former boundaries. *)

From mathcomp Require Import ssreflect ssrbool ssrnat eqtype seq.
From Wasm Require Import datatypes operations opsem memory extraction_instance binary_format_parser.
Require Import Strings.Byte.
Require Import BinNat.
Require Import ZArith.
Require Import Relations.Relation_Operators.
Require Import Relations.Operators_Properties.

Existing Instance Memory_instance.memory_instance.
Existing Instance Extraction_instance.hfc.
Existing Instance Extraction_instance.host_instance.

(* =====================================================================
   Section: bytes (formerly AddBytes.v)

   GENERATED -- do not edit this definition by hand. Produced by
   tools/wasm_bytes_to_coq.py from add.wasm. Regenerate via `make bytes`
   after any change to add.wat; the tool replaces only the text between
   the BEGIN/END markers below.
   ===================================================================== *)

(* BEGIN GENERATED BYTES *)
Definition add_wasm_bytes : list byte := x00 :: x61 :: x73 :: x6d :: x01 :: x00 :: x00 :: x00 :: x01 :: x07 :: x01 :: x60 :: x02 :: x7f :: x7f :: x01 :: x7f :: x03 :: x02 :: x01 :: x00 :: x07 :: x07 :: x01 :: x03 :: x61 :: x64 :: x64 :: x00 :: x00 :: x0a :: x09 :: x01 :: x07 :: x00 :: x20 :: x00 :: x20 :: x01 :: x6a :: x0b :: nil.
(* END GENERATED BYTES *)

(* =====================================================================
   Section: AST (formerly AddAst.v)

   Hand-encoded Coq AST for the add function defined in add.wat. This term
   is proved below (see "correspondence" section) to be byte-identical,
   via WasmCert-Coq's binary parser, to what wat2wasm actually compiles
   from add.wat -- so this term's correspondence with the .wat source is
   not merely asserted by eye, it is machine-checked. Local indices follow
   the .wat source: 0=$a (param) 1=$b (param).
   ===================================================================== *)

Definition l_a : localidx := 0%N.
Definition l_b : localidx := 1%N.

Definition add_body : list basic_instruction :=
  [:: BI_local_get l_a; BI_local_get l_b; BI_binop T_i32 (Binop_i BOI_add) ].

(* No non-parameter locals: modfunc_locals does not include the two
   parameters ($a, $b), which are supplied by function_type instead. *)
Definition add_locals : list value_type := [::].

Definition add_module_func : module_func :=
  {| modfunc_type := 0%N;
     modfunc_locals := add_locals;
     modfunc_body := add_body |}.

Definition add_function_type : function_type :=
  Tf [:: T_num T_i32; T_num T_i32] [:: T_num T_i32].

(* =====================================================================
   Section: correspondence (formerly AddCorrespondence.v)

   Trust chain: wat2wasm compiles add.wat -> add.wasm (trusted, external,
   outside Coq); tools/wasm_bytes_to_coq.py copies those exact bytes into
   add_wasm_bytes above (mechanical, no interpretation); WasmCert-Coq's
   binary parser (also outside the kernel's soundness argument, but its
   *output* here is checked *by* the kernel) turns those bytes into a
   `module` AST. This section proves, by kernel-checked computation, that
   the parsed function is identical to add_module_func -- the term every
   other section in this file is actually about. That closes the "did I
   transcribe the .wat correctly into Coq" gap: from here on,
   add_module_func is provably what wat2wasm actually produced from
   add.wat, not just a lookalike.
   ===================================================================== *)

Definition parsed_module : option module := run_parse_module add_wasm_bytes.

Lemma add_wasm_parses : exists m, parsed_module = Some m.
Proof. eexists. vm_compute. reflexivity. Qed.

Lemma add_wasm_func_matches :
  match parsed_module with
  | Some m => List.nth_error m.(mod_funcs) 0 = Some add_module_func
  | None => False
  end.
Proof. vm_compute. reflexivity. Qed.

Lemma add_wasm_type_matches :
  match parsed_module with
  | Some m => List.nth_error m.(mod_types) 0 = Some add_function_type
  | None => False
  end.
Proof. vm_compute. reflexivity. Qed.

(* =====================================================================
   Section: invocation setup (formerly AddInvoke.v)

   A minimal store/frame/function-closure and initial configuration for
   invoking add_module_func via the real reduce/reduce_trans semantics,
   skipping WasmCert-Coq's generic module-instantiation machinery
   (module_typing/instantiate/alloc_module), which is orthogonal
   boilerplate already proven sound upstream and not specific to what this
   add function actually does. There are no host function calls and no
   memory anywhere in add_module_func (add.wat declares no memory), so we
   reuse WasmCert-Coq's own ready-made "no host functions" instances
   (host_function := void) from extraction_instance.v rather than
   inventing new ones.
   ===================================================================== *)

Definition add_moduleinst : moduleinst :=
  {| inst_types := [:: add_function_type];
     inst_funcs := [:: 0%N];
     inst_tables := [::];
     inst_mems := [::];
     inst_globals := [::];
     inst_elems := [::];
     inst_datas := [::];
     inst_exports := [::] |}.

Definition initial_store : store_record :=
  {| s_funcs := [:: FC_func_native add_function_type add_moduleinst add_module_func];
     s_tables := [::];
     s_mems := [::];
     s_globals := [::];
     s_elems := [::];
     s_datas := [::] |}.

Definition initial_frame : frame := {| f_locs := [::]; f_inst := add_moduleinst |}.

(* The invoked function takes ($a $b) as i32 arguments off the stack,
   immediately followed by AI_invoke of function address 0 (the only
   function in our hand-built store). *)
Definition initial_config (a b : Wasm_int.Int32.int)
  : host_state * store_record * frame * list administrative_instruction :=
  (tt, initial_store, initial_frame,
   [:: AI_basic (BI_const_num (VAL_int32 a));
       AI_basic (BI_const_num (VAL_int32 b));
       AI_invoke 0%N]).

(* =====================================================================
   Section: small-step infrastructure (formerly AddSteps.v)

   Small-step reasoning infrastructure, and the specific atomic-instruction
   lemmas needed for add_body = [local.get $a; local.get $b; i32.add]. The
   general-purpose lemmas here (reduce_trans_label, reduce_trans_frame,
   step1, steps_trans, prepend1) are not specific to this function; they
   are the same machinery WasmCert-Coq's own r_label/r_frame congruence
   rules only provide a single-step version of.
   ===================================================================== *)

Lemma reduce_trans_label :
  forall k (lh : lholed k) hs s f es hs' s' f' es',
    reduce_trans (hs, s, f, es) (hs', s', f', es') ->
    reduce_trans (hs, s, f, lfill lh es) (hs', s', f', lfill lh es').
Proof.
  intros k lh hs s f es hs' s' f' es' H.
  unfold reduce_trans in *.
  apply clos_rt_rt1n_iff.
  apply clos_rt_rt1n_iff in H.
  remember (hs, s, f, es) as X eqn:HeqX.
  remember (hs', s', f', es') as Y eqn:HeqY.
  revert hs s f es hs' s' f' es' HeqX HeqY.
  induction H as [X | X Ymid Z Hstep Hrest IH]; intros hs s f es hs' s' f' es' HeqX HeqY; subst.
  - inversion HeqY; subst. apply rt1n_refl.
  - destruct Ymid as [[[hsm sm] fm] esm].
    unfold reduce_tuple in Hstep.
    eapply Relation_Operators.rt1n_trans with (y := (hsm, sm, fm, lfill lh esm)).
    + eapply r_label. exact Hstep. reflexivity. reflexivity.
    + eapply (IH hsm sm fm esm hs' s' f' es'); reflexivity.
Qed.

Lemma reduce_trans_frame :
  forall hs s f0 n f es hs' s' f' es',
    reduce_trans (hs, s, f, es) (hs', s', f', es') ->
    reduce_trans (hs, s, f0, [:: AI_frame n f es]) (hs', s', f0, [:: AI_frame n f' es']).
Proof.
  intros hs s f0 n f es hs' s' f' es' H.
  unfold reduce_trans in *.
  apply clos_rt_rt1n_iff.
  apply clos_rt_rt1n_iff in H.
  remember (hs, s, f, es) as X eqn:HeqX.
  remember (hs', s', f', es') as Y eqn:HeqY.
  revert hs s f es hs' s' f' es' HeqX HeqY.
  induction H as [X | X Ymid Z Hstep Hrest IH]; intros hs s f es hs' s' f' es' HeqX HeqY; subst.
  - inversion HeqY; subst. apply rt1n_refl.
  - destruct Ymid as [[[hsm sm] fm] esm].
    unfold reduce_tuple in Hstep.
    eapply Relation_Operators.rt1n_trans with (y := (hsm, sm, f0, [:: AI_frame n fm esm])).
    + apply r_frame. exact Hstep.
    + eapply (IH hsm sm fm esm hs' s' f' es'); reflexivity.
Qed.

Lemma step1 :
  forall hs s f es hs' s' f' es' (rest : seq administrative_instruction),
    reduce hs s f es hs' s' f' es' ->
    reduce_trans (hs, s, f, es ++ rest) (hs', s', f', es' ++ rest).
Proof.
  intros hs s f es hs' s' f' es' rest Hred.
  pose proof (reduce_trans_label 0 (LH_base [::] rest) hs s f es hs' s' f' es') as Hlift.
  simpl in Hlift.
  apply Hlift.
  apply Relation_Operators.rt_step.
  unfold reduce_tuple. exact Hred.
Qed.

Lemma steps_trans :
  forall hs s f es hs1 s1 f1 es1 hs2 s2 f2 es2,
    reduce_trans (hs, s, f, es) (hs1, s1, f1, es1) ->
    reduce_trans (hs1, s1, f1, es1) (hs2, s2, f2, es2) ->
    reduce_trans (hs, s, f, es) (hs2, s2, f2, es2).
Proof.
  intros. unfold reduce_trans in *. eapply Relation_Operators.rt_trans; eauto.
Qed.

Lemma reduce_trans_prepend :
  forall hs s f es hs' s' f' es' (vs : list value),
    reduce_trans (hs, s, f, es) (hs', s', f', es') ->
    reduce_trans (hs, s, f, v_to_e_list vs ++ es) (hs', s', f', v_to_e_list vs ++ es').
Proof.
  intros hs s f es hs' s' f' es' vs H.
  pose proof (reduce_trans_label 0 (LH_base vs [::]) hs s f es hs' s' f' es' H) as Hlift.
  simpl in Hlift. rewrite !cats0 in Hlift. exact Hlift.
Qed.

Lemma prepend1 :
  forall hs s f v es hs' s' f' es',
    reduce_trans (hs, s, f, es) (hs', s', f', es') ->
    reduce_trans (hs, s, f, v_to_e v :: es) (hs', s', f', v_to_e v :: es').
Proof.
  intros hs s f v es hs' s' f' es' H.
  exact (reduce_trans_prepend hs s f es hs' s' f' es' [:: v] H).
Qed.

Lemma lift_through_label_n :
  forall n hs s f es hs' s' f' es' rest,
    reduce_trans (hs, s, f, es) (hs', s', f', es') ->
    reduce_trans (hs, s, f, AI_label n [::] es :: rest) (hs', s', f', AI_label n [::] es' :: rest).
Proof.
  intros n hs s f es hs' s' f' es' rest H.
  pose proof (reduce_trans_label 1 (LH_rec [::] n [::] (LH_base [::] [::]) rest)
                hs s f es hs' s' f' es' H) as Hlift.
  simpl in Hlift. rewrite ?cats0 in Hlift.
  exact Hlift.
Qed.

(* ----- Atomic instruction steps. ----- *)

Lemma step_local_get :
  forall hs s f j v rest,
    lookup_N f.(f_locs) j = Some v ->
    reduce_trans (hs, s, f, AI_basic (BI_local_get j) :: rest) (hs, s, f, v_to_e v :: rest).
Proof.
  intros hs s f j v rest Hlookup.
  apply (step1 hs s f [:: AI_basic (BI_local_get j)] hs s f [:: v_to_e v] rest).
  apply r_local_get. exact Hlookup.
Qed.

Lemma step_binop_i32 :
  forall hs s f op v1 v2 v rest,
    app_binop (Binop_i op) (VAL_int32 v1) (VAL_int32 v2) = Some (VAL_int32 v) ->
    reduce_trans (hs, s, f, $VN (VAL_int32 v1) :: $VN (VAL_int32 v2) :: AI_basic (BI_binop T_i32 (Binop_i op)) :: rest)
                 (hs, s, f, $VN (VAL_int32 v) :: rest).
Proof.
  intros hs s f op v1 v2 v rest Happ.
  apply (step1 hs s f [:: $VN (VAL_int32 v1); $VN (VAL_int32 v2); AI_basic (BI_binop T_i32 (Binop_i op))]
           hs s f [:: $VN (VAL_int32 v)] rest).
  apply r_simple.
  eapply rs_binop_success; [reflexivity | exact Happ].
Qed.

(* =====================================================================
   Section: top-level correctness (formerly AddCorrect.v)

   Invoking add_module_func through WasmCert-Coq's real small-step
   semantics, on any two i32 arguments, reduces to a single value equal to
   Wasm_int.Int32.iadd of those arguments -- i.e. exactly the 32-bit
   wrapping addition the Wasm spec defines i32.add to perform. A corollary
   restates that in "textbook" unsigned-integer-mod-2^32 terms.
   ===================================================================== *)

Open Scope Z_scope.

Definition mkframe (a b : value) : frame := {| f_locs := [:: a; b]; f_inst := add_moduleinst |}.

(* r_invoke_native, specialised to our single hand-built function: pops the
   two i32 arguments into locals 0/1 (add_locals = [::], so there are no
   extra locals to default-fill), and enters a fresh frame wrapping a fresh
   (arity-1, matching the single i32 result) label around the function
   body. *)
Lemma step_invoke :
  forall hs (a b : Wasm_int.Int32.int) rest,
    reduce_trans
      (hs, initial_store, initial_frame,
       [:: AI_basic (BI_const_num (VAL_int32 a));
           AI_basic (BI_const_num (VAL_int32 b));
           AI_invoke 0%N] ++ rest)
      (hs, initial_store, initial_frame,
       [:: AI_frame 1 (mkframe (VAL_num (VAL_int32 a)) (VAL_num (VAL_int32 b)))
             [:: AI_label 1 [::] (to_e_list add_body)]] ++ rest).
Proof.
  intros hs a b rest.
  apply (step1 hs initial_store initial_frame
           [:: AI_basic (BI_const_num (VAL_int32 a));
               AI_basic (BI_const_num (VAL_int32 b));
               AI_invoke 0%N]
           hs initial_store initial_frame
           [:: AI_frame 1 (mkframe (VAL_num (VAL_int32 a)) (VAL_num (VAL_int32 b)))
                 [:: AI_label 1 [::] (to_e_list add_body)]]
           rest).
  eapply (r_invoke_native (addr := 0%N)
            (ves := [:: AI_basic (BI_const_num (VAL_int32 a)); AI_basic (BI_const_num (VAL_int32 b))])
            (vs := [:: VAL_num (VAL_int32 a); VAL_num (VAL_int32 b)]));
    reflexivity.
Qed.

(* The function body itself: local.get $a; local.get $b; i32.add. *)
Lemma add_body_runs :
  forall hs s (a b : Wasm_int.Int32.int) rest,
    reduce_trans
      (hs, s, mkframe (VAL_num (VAL_int32 a)) (VAL_num (VAL_int32 b)), to_e_list add_body ++ rest)
      (hs, s, mkframe (VAL_num (VAL_int32 a)) (VAL_num (VAL_int32 b)),
       $VN (VAL_int32 (Wasm_int.Int32.iadd a b)) :: rest).
Proof.
  intros hs s a b rest.
  set (f0 := mkframe (VAL_num (VAL_int32 a)) (VAL_num (VAL_int32 b))).
  unfold add_body.
  eapply steps_trans.
  { apply (step_local_get hs s f0 l_a (VAL_num (VAL_int32 a))). reflexivity. }
  eapply steps_trans.
  { apply prepend1.
    apply (step_local_get hs s f0 l_b (VAL_num (VAL_int32 b))). reflexivity. }
  apply (step_binop_i32 hs s f0 BOI_add a b (Wasm_int.Int32.iadd a b)).
  reflexivity.
Qed.

Theorem add_correct :
  forall (a b : Wasm_int.Int32.int),
    reduce_trans (initial_config a b)
                 (tt, initial_store, initial_frame, [:: v_to_e (VAL_num (VAL_int32 (Wasm_int.Int32.iadd a b)))]).
Proof.
  intros a b.
  unfold initial_config.
  eapply steps_trans.
  { apply (step_invoke tt a b [::]). }
  eapply steps_trans.
  { eapply reduce_trans_frame.
    eapply steps_trans.
    { eapply lift_through_label_n. apply (add_body_runs tt initial_store a b [::]). }
    apply (step1 tt initial_store (mkframe (VAL_num (VAL_int32 a)) (VAL_num (VAL_int32 b)))
             [:: AI_label 1 [::] [:: $VN (VAL_int32 (Wasm_int.Int32.iadd a b))]]
             tt initial_store (mkframe (VAL_num (VAL_int32 a)) (VAL_num (VAL_int32 b)))
             [:: $VN (VAL_int32 (Wasm_int.Int32.iadd a b))] [::]).
    apply r_simple. apply rs_label_const. reflexivity. }
  apply (step1 tt initial_store initial_frame
           [:: AI_frame 1 (mkframe (VAL_num (VAL_int32 a)) (VAL_num (VAL_int32 b)))
                 [:: $VN (VAL_int32 (Wasm_int.Int32.iadd a b))]]
           tt initial_store initial_frame
           [:: $VN (VAL_int32 (Wasm_int.Int32.iadd a b))] [::]).
  apply r_simple. eapply rs_local_const; reflexivity.
Qed.

(* Corollary: restated as plain unsigned-integer addition mod 2^32, the
   ordinary "textbook" meaning of what an i32 add instruction computes. *)
Corollary add_correct_unsigned :
  forall (a b : Wasm_int.Int32.int),
    exists final_store final_frame,
      reduce_trans (initial_config a b)
                   (tt, final_store, final_frame,
                    [:: v_to_e (VAL_num (VAL_int32 (Wasm_int.Int32.iadd a b)))]) /\
      Wasm_int.Int32.unsigned (Wasm_int.Int32.iadd a b) =
        (Wasm_int.Int32.unsigned a + Wasm_int.Int32.unsigned b) mod Wasm_int.Int32.modulus.
Proof.
  intros a b.
  exists initial_store, initial_frame.
  split.
  - apply add_correct.
  - unfold Wasm_int.Int32.iadd.
    rewrite Wasm_int.Int32.add_unsigned.
    apply Wasm_int.Int32.unsigned_repr_eq.
Qed.
