#!/usr/bin/env python3
"""Regenerate the GENERATED BYTES definition inside coq/Add.v from a .wasm file.

Usage: wasm_bytes_to_coq.py <input.wasm> <target.v> <coq-def-name>

Replaces the single line between the
`(* BEGIN GENERATED BYTES *)` / `(* END GENERATED BYTES *)` markers in
<target.v> with a fresh `Definition <coq-def-name> : list byte := ...`
literal built from <input.wasm>'s exact bytes, leaving the rest of the file
(the hand-written AST, proofs, etc.) untouched.
"""
import sys

BEGIN_MARKER = "(* BEGIN GENERATED BYTES *)"
END_MARKER = "(* END GENERATED BYTES *)"


def main() -> None:
    if len(sys.argv) != 4:
        print(f"usage: {sys.argv[0]} <input.wasm> <target.v> <coq-def-name>", file=sys.stderr)
        sys.exit(1)

    in_path, target_path, def_name = sys.argv[1], sys.argv[2], sys.argv[3]

    with open(in_path, "rb") as f:
        data = f.read()

    # WasmCert-Coq's binary_format_parser.v consumes Coq stdlib's
    # `Strings.Byte.byte` (256 constructors `x00`..`xff`), which is a
    # *different* type from WasmCert-Coq's own `bytes.v` byte (an alias for
    # CompCert's Integers.byte, used inside the AST/memory model). The
    # parser's token type shadows the Wasm one via import order, so this
    # definition must use the stdlib hex constructors, not `%N` numerals.
    items = " :: ".join(f"x{b:02x}" for b in data)
    new_def = f"Definition {def_name} : list byte := {items} :: nil."

    with open(target_path) as f:
        text = f.read()

    start = text.index(BEGIN_MARKER) + len(BEGIN_MARKER)
    end = text.index(END_MARKER)
    text = text[:start] + "\n" + new_def + "\n" + text[end:]

    with open(target_path, "w") as f:
        f.write(text)

    print(f"updated {target_path}'s {def_name} from {in_path} ({len(data)} bytes)")


if __name__ == "__main__":
    main()
